### ISSUE TITLE
Homebrew issue 

### ISSUE THREAD

**Issue by aegis123** [lokalise/lokalise-cli-2-go#85]
When calling brew upgrade I get the following message so creating an issue for that.

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the lokalise/cli-2 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/lokalise/homebrew-cli-2/Formula/lokalise2.rb:9
```

**Comment by arshiacont** [comment]
Any progress on this? we are having the same issue

**Comment by shuguenot** [comment]
up

**Comment by nuhkoca** [comment]
This [PR](https://github.com/lokalise/homebrew-cli-2/pull/4) should fix this issue. Can you confirm?

**Comment by arshiacont** [comment]
We are still getting an error on Command Line Tools saying it's "too outdated" (we are on XCode 13.2 and the brew install asks for 13.1 ! 
```
~ brew install lokalise2
==> Downloading https://github.com/lokalise/lokalise-cli-2-go/releases/download/
Already downloaded: /Users/acont/Library/Caches/Homebrew/downloads/9a3690aba83e724fcf07f6431fb9fcb47ad0acb4432971974a6f529e85b0dca0--lokalise2_darwin_x86_64.tar.gz
==> Installing lokalise2 from lokalise/cli-2
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.
```

**Comment by aegis123** [comment]
I don't see the message anymore with 2.6.8
